language: python
python:
- '3.5'
- '3.6'
install: "pip install -r dev_requirements.txt && pip install -r requirements.txt"

script: coverage run --branch --source=generank ./manage.py test

after_success: coveralls
