language: python
python:
- '3.5'
- '3.6'
install: "pip install -r dev_requirements.txt && pip install -r requirements.txt"

script: ./manage.py test --with-cov --cover-package=generank

after_success: coveralls
